/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  documentationSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = {
    main: [
        'overview',
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                'getting-started/first-steps',
                'getting-started/a-quick-tour',
                'getting-started/what-to-expect',
            ],
        },
        {
            type: 'category',
            label: 'Collaboration',
            items: [
                'collaboration/git-gud',
                'collaboration/development-etiquette',
                'collaboration/crafting-a-good-pull-request',
                'collaboration/reviewing-a-pull-request',
                'collaboration/common-pull-request-issues',
                'collaboration/pair-programming',
            ],
        },
        {
            type: 'category',
            label: 'Style Guides',
            items: [
//              'manual-installation',
//              'manual-installation/android',
//              'manual-installation/ios',
//              'manual-installation/macos',
                {
                    type: 'link',
                    label: 'Technical Writing Guide',
                    href: 'https://developers.google.com/tech-writing',
                },
            ],
        },
        'further-reading',
    ]
//        'Home': {
//        },

//        'Getting Started': [
//          'overview',
//          'cli',
//          {
//            type: 'category',
//            label: 'Manual Installation',
//            items: [
//              'manual-installation',
//              'manual-installation/android',
//              'manual-installation/ios',
//              'manual-installation/macos',
//              'manual-installation/web',
//            ],
//          },
//          'migration',
//        ],
};
